language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - DRUPAL_CORE=8.0.x
  - DRUPAL_CORE=8.1.x

mysql:
  database: og
  username: root
  encoding: utf8

before_script:
  # Remember the current rules test directory for later use in the Drupal
  # installation.
  - TESTDIR=$(pwd)
  # Navigate out of module directory to prevent blown stack by recursive module
  # lookup.
  - cd ..

  # Create database.
  - mysql -e 'create database og'
  # Download Drupal 8 core.
  - git clone --branch $DRUPAL_CORE --depth 1 http://git.drupal.org/project/drupal.git
  - cd drupal

  - ln -s $TESTDIR modules/og

  # Adding DB so PHPUnit could mock the environment.
  - export SIMPLETEST_DB=mysql://root:@127.0.0.1/og;

script:
  # Run the PHPUnit tests which also include the kernel tests.
  - ./vendor/phpunit/phpunit/phpunit -c ./core/phpunit.xml.dist ./modules/og
